#!/bin/bash

# change to this directory
cd "$(dirname "${BASH_SOURCE[0]}")" || exit

akdc create -c east-ga-south-101 -q -l eastus &
akdc create -c east-ga-south-102 -q -l eastus &
akdc create -c east-ga-south-103 -q -l eastus &
akdc create -c east-ga-south-104 -q -l eastus &
akdc create -c east-ga-south-105 -q -l eastus &
akdc create -c east-nc-charlotte-101 -q -l eastus &
akdc create -c east-nc-charlotte-102 -q -l eastus &
akdc create -c east-nc-charlotte-103 -q -l eastus &
akdc create -c east-nc-charlotte-104 -q -l eastus &
akdc create -c east-nc-charlotte-105 -q -l eastus &
akdc create -c east-nc-durham-101 -q -l eastus &
akdc create -c east-nc-durham-102 -q -l eastus &
akdc create -c east-nc-durham-103 -q -l eastus &
akdc create -c east-nc-durham-104 -q -l eastus &
akdc create -c east-nc-durham-105 -q -l eastus &
akdc create -c east-nc-east-101 -q -l eastus &
akdc create -c east-nc-east-102 -q -l eastus &
akdc create -c east-nc-east-103 -q -l eastus &
akdc create -c east-nc-east-104 -q -l eastus &
akdc create -c east-nc-east-105 -q -l eastus &
akdc create -c east-nc-raleigh-101 -q -l eastus &
akdc create -c east-nc-raleigh-102 -q -l eastus &
akdc create -c east-nc-raleigh-103 -q -l eastus &
akdc create -c east-nc-raleigh-104 -q -l eastus &
akdc create -c east-nc-raleigh-105 -q -l eastus &
akdc create -c east-nc-west-101 -q -l eastus &
akdc create -c east-nc-west-102 -q -l eastus &
akdc create -c east-nc-west-103 -q -l eastus &
akdc create -c east-nc-west-104 -q -l eastus &
akdc create -c east-nc-west-105 -q -l eastus &

akdc create -c west-ca-la-101 -q -l westus &
akdc create -c west-ca-la-102 -q -l westus &
akdc create -c west-ca-la-103 -q -l westus &
akdc create -c west-ca-la-104 -q -l westus &
akdc create -c west-ca-la-105 -q -l westus &
akdc create -c west-ca-north-101 -q -l westus &
akdc create -c west-ca-north-102 -q -l westus &
akdc create -c west-ca-north-103 -q -l westus &
akdc create -c west-ca-north-104 -q -l westus &
akdc create -c west-ca-north-105 -q -l westus &
akdc create -c west-ca-sac-101 -q -l westus &
akdc create -c west-ca-sac-102 -q -l westus &
akdc create -c west-ca-sac-103 -q -l westus &
akdc create -c west-ca-sac-104 -q -l westus &
akdc create -c west-ca-sac-105 -q -l westus &
akdc create -c west-ca-sand-101 -q -l westus &
akdc create -c west-ca-sand-102 -q -l westus &
akdc create -c west-ca-sand-103 -q -l westus &
akdc create -c west-ca-sand-104 -q -l westus &
akdc create -c west-ca-sand-105 -q -l westus &
akdc create -c west-ca-sfo-101 -q -l westus &
akdc create -c west-ca-sfo-102 -q -l westus &
akdc create -c west-ca-sfo-103 -q -l westus &
akdc create -c west-ca-sfo-104 -q -l westus &
akdc create -c west-ca-sfo-105 -q -l westus &
akdc create -c west-ca-south-101 -q -l westus &
akdc create -c west-ca-south-102 -q -l westus &
akdc create -c west-ca-south-103 -q -l westus &
akdc create -c west-ca-south-104 -q -l westus &
akdc create -c west-ca-south-105 -q -l westus &
akdc create -c west-ca-west-101 -q -l westus &
akdc create -c west-ca-west-102 -q -l westus &
akdc create -c west-ca-west-103 -q -l westus &
akdc create -c west-ca-west-104 -q -l westus &
akdc create -c west-ca-west-105 -q -l westus &
akdc create -c west-wa-central-101 -q -l westus &
akdc create -c west-wa-central-102 -q -l westus &
akdc create -c west-wa-central-103 -q -l westus &
akdc create -c west-wa-central-104 -q -l westus &
akdc create -c west-wa-central-105 -q -l westus &
akdc create -c west-wa-east-101 -q -l westus &
akdc create -c west-wa-east-102 -q -l westus &
akdc create -c west-wa-east-103 -q -l westus &
akdc create -c west-wa-east-104 -q -l westus &
akdc create -c west-wa-east-105 -q -l westus &
akdc create -c west-wa-olympia-101 -q -l westus &
akdc create -c west-wa-olympia-102 -q -l westus &
akdc create -c west-wa-olympia-103 -q -l westus &
akdc create -c west-wa-olympia-104 -q -l westus &
akdc create -c west-wa-olympia-105 -q -l westus &
akdc create -c west-wa-sea-101 -q -l westus &
akdc create -c west-wa-sea-102 -q -l westus &
akdc create -c west-wa-sea-103 -q -l westus &
akdc create -c west-wa-sea-104 -q -l westus &
akdc create -c west-wa-sea-105 -q -l westus &
akdc create -c west-wa-spokane-101 -q -l westus &
akdc create -c west-wa-spokane-102 -q -l westus &
akdc create -c west-wa-spokane-103 -q -l westus &
akdc create -c west-wa-spokane-104 -q -l westus &
akdc create -c west-wa-spokane-105 -q -l westus &
akdc create -c west-wa-tacoma-101 -q -l westus &
akdc create -c west-wa-tacoma-102 -q -l westus &
akdc create -c west-wa-tacoma-103 -q -l westus &
akdc create -c west-wa-tacoma-104 -q -l westus &
akdc create -c west-wa-tacoma-105 -q -l westus &
akdc create -c west-wa-west-101 -q -l westus &
akdc create -c west-wa-west-102 -q -l westus &
akdc create -c west-wa-west-103 -q -l westus &
akdc create -c west-wa-west-104 -q -l westus &
akdc create -c west-wa-west-105 -q -l westus &
