#!/bin/bash

# change to this directory
cd "$(dirname "${BASH_SOURCE[0]}")" || exit

akdc create -c central-ks-kc-101 -q -l centralus &
akdc create -c central-ks-kc-102 -q -l centralus &
akdc create -c central-ks-kc-103 -q -l centralus &
akdc create -c central-ks-kc-104 -q -l centralus &
akdc create -c central-ks-kc-105 -q -l centralus &
akdc create -c central-ks-wichita-101 -q -l centralus &
akdc create -c central-ks-wichita-102 -q -l centralus &
akdc create -c central-ks-wichita-103 -q -l centralus &
akdc create -c central-ks-wichita-104 -q -l centralus &
akdc create -c central-ks-wichita-105 -q -l centralus &
akdc create -c central-mo-columbia-101 -q -l centralus &
akdc create -c central-mo-columbia-102 -q -l centralus &
akdc create -c central-mo-columbia-103 -q -l centralus &
akdc create -c central-mo-columbia-104 -q -l centralus &
akdc create -c central-mo-columbia-105 -q -l centralus &
akdc create -c central-mo-east-101 -q -l centralus &
akdc create -c central-mo-east-102 -q -l centralus &
akdc create -c central-mo-east-103 -q -l centralus &
akdc create -c central-mo-east-104 -q -l centralus &
akdc create -c central-mo-east-105 -q -l centralus &
akdc create -c central-mo-north-101 -q -l centralus &
akdc create -c central-mo-north-102 -q -l centralus &
akdc create -c central-mo-north-103 -q -l centralus &
akdc create -c central-mo-north-104 -q -l centralus &
akdc create -c central-mo-north-105 -q -l centralus &
akdc create -c central-mo-south-101 -q -l centralus &
akdc create -c central-mo-south-102 -q -l centralus &
akdc create -c central-mo-south-103 -q -l centralus &
akdc create -c central-mo-south-104 -q -l centralus &
akdc create -c central-mo-south-105 -q -l centralus &
akdc create -c central-mo-stlouis-101 -q -l centralus &
akdc create -c central-mo-stlouis-102 -q -l centralus &
akdc create -c central-mo-stlouis-103 -q -l centralus &
akdc create -c central-mo-stlouis-104 -q -l centralus &
akdc create -c central-mo-stlouis-105 -q -l centralus &
akdc create -c central-mo-west-101 -q -l centralus &
akdc create -c central-mo-west-102 -q -l centralus &
akdc create -c central-mo-west-103 -q -l centralus &
akdc create -c central-mo-west-104 -q -l centralus &
akdc create -c central-mo-west-105 -q -l centralus &
akdc create -c central-tx-aus-101 -q -l centralus &
akdc create -c central-tx-aus-102 -q -l centralus &
akdc create -c central-tx-aus-103 -q -l centralus &
akdc create -c central-tx-aus-104 -q -l centralus &
akdc create -c central-tx-aus-105 -q -l centralus &
akdc create -c central-tx-dallas-101 -q -l centralus &
akdc create -c central-tx-dallas-102 -q -l centralus &
akdc create -c central-tx-dallas-103 -q -l centralus &
akdc create -c central-tx-dallas-104 -q -l centralus &
akdc create -c central-tx-dallas-105 -q -l centralus &
akdc create -c central-tx-east-101 -q -l centralus &
akdc create -c central-tx-east-102 -q -l centralus &
akdc create -c central-tx-east-103 -q -l centralus &
akdc create -c central-tx-east-104 -q -l centralus &
akdc create -c central-tx-east-105 -q -l centralus &
akdc create -c central-tx-houston-101 -q -l centralus &
akdc create -c central-tx-houston-102 -q -l centralus &
akdc create -c central-tx-houston-103 -q -l centralus &
akdc create -c central-tx-houston-104 -q -l centralus &
akdc create -c central-tx-houston-105 -q -l centralus &
akdc create -c central-tx-north-101 -q -l centralus &
akdc create -c central-tx-north-102 -q -l centralus &
akdc create -c central-tx-north-103 -q -l centralus &
akdc create -c central-tx-north-104 -q -l centralus &
akdc create -c central-tx-north-105 -q -l centralus &
akdc create -c central-tx-san-101 -q -l centralus &
akdc create -c central-tx-san-102 -q -l centralus &
akdc create -c central-tx-san-103 -q -l centralus &
akdc create -c central-tx-san-104 -q -l centralus &
akdc create -c central-tx-san-105 -q -l centralus &
akdc create -c central-tx-south-101 -q -l centralus &
akdc create -c central-tx-south-102 -q -l centralus &
akdc create -c central-tx-south-103 -q -l centralus &
akdc create -c central-tx-south-104 -q -l centralus &
akdc create -c central-tx-south-105 -q -l centralus &
akdc create -c central-tx-west-101 -q -l centralus &
akdc create -c central-tx-west-102 -q -l centralus &
akdc create -c central-tx-west-103 -q -l centralus &
akdc create -c central-tx-west-104 -q -l centralus &
akdc create -c central-tx-west-105 -q -l centralus &

akdc create -c east-ga-albany-101 -q -l eastus &
akdc create -c east-ga-albany-102 -q -l eastus &
akdc create -c east-ga-albany-103 -q -l eastus &
akdc create -c east-ga-albany-104 -q -l eastus &
akdc create -c east-ga-albany-105 -q -l eastus &
akdc create -c east-ga-athens-101 -q -l eastus &
akdc create -c east-ga-athens-102 -q -l eastus &
akdc create -c east-ga-athens-103 -q -l eastus &
akdc create -c east-ga-athens-104 -q -l eastus &
akdc create -c east-ga-athens-105 -q -l eastus &
akdc create -c east-ga-atl-101 -q -l eastus &
akdc create -c east-ga-atl-102 -q -l eastus &
akdc create -c east-ga-atl-103 -q -l eastus &
akdc create -c east-ga-atl-104 -q -l eastus &
akdc create -c east-ga-atl-105 -q -l eastus &
akdc create -c east-ga-north-101 -q -l eastus &
akdc create -c east-ga-north-102 -q -l eastus &
akdc create -c east-ga-north-103 -q -l eastus &
akdc create -c east-ga-north-104 -q -l eastus &
akdc create -c east-ga-north-105 -q -l eastus &
