#!/bin/bash

az group delete -y --no-wait -g central-ks-kc-101 &
az group delete -y --no-wait -g central-ks-kc-102 &
az group delete -y --no-wait -g central-ks-kc-103 &
az group delete -y --no-wait -g central-ks-kc-104 &
az group delete -y --no-wait -g central-ks-kc-105 &
az group delete -y --no-wait -g central-ks-wichita-101 &
az group delete -y --no-wait -g central-ks-wichita-102 &
az group delete -y --no-wait -g central-ks-wichita-103 &
az group delete -y --no-wait -g central-ks-wichita-104 &
az group delete -y --no-wait -g central-ks-wichita-105 &
az group delete -y --no-wait -g central-mo-columbia-101 &
az group delete -y --no-wait -g central-mo-columbia-102 &
az group delete -y --no-wait -g central-mo-columbia-103 &
az group delete -y --no-wait -g central-mo-columbia-104 &
az group delete -y --no-wait -g central-mo-columbia-105 &
az group delete -y --no-wait -g central-mo-east-101 &
az group delete -y --no-wait -g central-mo-east-102 &
az group delete -y --no-wait -g central-mo-east-103 &
az group delete -y --no-wait -g central-mo-east-104 &
az group delete -y --no-wait -g central-mo-east-105 &
az group delete -y --no-wait -g central-mo-north-101 &
az group delete -y --no-wait -g central-mo-north-102 &
az group delete -y --no-wait -g central-mo-north-103 &
az group delete -y --no-wait -g central-mo-north-104 &
az group delete -y --no-wait -g central-mo-north-105 &
az group delete -y --no-wait -g central-mo-south-101 &
az group delete -y --no-wait -g central-mo-south-102 &
az group delete -y --no-wait -g central-mo-south-103 &
az group delete -y --no-wait -g central-mo-south-104 &
az group delete -y --no-wait -g central-mo-south-105 &
az group delete -y --no-wait -g central-mo-stlouis-101 &
az group delete -y --no-wait -g central-mo-stlouis-102 &
az group delete -y --no-wait -g central-mo-stlouis-103 &
az group delete -y --no-wait -g central-mo-stlouis-104 &
az group delete -y --no-wait -g central-mo-stlouis-105 &
az group delete -y --no-wait -g central-mo-west-101 &
az group delete -y --no-wait -g central-mo-west-102 &
az group delete -y --no-wait -g central-mo-west-103 &
az group delete -y --no-wait -g central-mo-west-104 &
az group delete -y --no-wait -g central-mo-west-105 &
az group delete -y --no-wait -g central-tx-aus-101 &
az group delete -y --no-wait -g central-tx-aus-102 &
az group delete -y --no-wait -g central-tx-aus-103 &
az group delete -y --no-wait -g central-tx-aus-104 &
az group delete -y --no-wait -g central-tx-aus-105 &
az group delete -y --no-wait -g central-tx-dallas-101 &
az group delete -y --no-wait -g central-tx-dallas-102 &
az group delete -y --no-wait -g central-tx-dallas-103 &
az group delete -y --no-wait -g central-tx-dallas-104 &
az group delete -y --no-wait -g central-tx-dallas-105 &
az group delete -y --no-wait -g central-tx-east-101 &
az group delete -y --no-wait -g central-tx-east-102 &
az group delete -y --no-wait -g central-tx-east-103 &
az group delete -y --no-wait -g central-tx-east-104 &
az group delete -y --no-wait -g central-tx-east-105 &
az group delete -y --no-wait -g central-tx-houston-101 &
az group delete -y --no-wait -g central-tx-houston-102 &
az group delete -y --no-wait -g central-tx-houston-103 &
az group delete -y --no-wait -g central-tx-houston-104 &
az group delete -y --no-wait -g central-tx-houston-105 &
az group delete -y --no-wait -g central-tx-north-101 &
az group delete -y --no-wait -g central-tx-north-102 &
az group delete -y --no-wait -g central-tx-north-103 &
az group delete -y --no-wait -g central-tx-north-104 &
az group delete -y --no-wait -g central-tx-north-105 &
az group delete -y --no-wait -g central-tx-san-101 &
az group delete -y --no-wait -g central-tx-san-102 &
az group delete -y --no-wait -g central-tx-san-103 &
az group delete -y --no-wait -g central-tx-san-104 &
az group delete -y --no-wait -g central-tx-san-105 &
az group delete -y --no-wait -g central-tx-south-101 &
az group delete -y --no-wait -g central-tx-south-102 &
az group delete -y --no-wait -g central-tx-south-103 &
az group delete -y --no-wait -g central-tx-south-104 &
az group delete -y --no-wait -g central-tx-south-105 &
az group delete -y --no-wait -g central-tx-west-101 &
az group delete -y --no-wait -g central-tx-west-102 &
az group delete -y --no-wait -g central-tx-west-103 &
az group delete -y --no-wait -g central-tx-west-104 &
az group delete -y --no-wait -g central-tx-west-105 &
az group delete -y --no-wait -g east-ga-albany-101 &
az group delete -y --no-wait -g east-ga-albany-102 &
az group delete -y --no-wait -g east-ga-albany-103 &
az group delete -y --no-wait -g east-ga-albany-104 &
az group delete -y --no-wait -g east-ga-albany-105 &
az group delete -y --no-wait -g east-ga-athens-101 &
az group delete -y --no-wait -g east-ga-athens-102 &
az group delete -y --no-wait -g east-ga-athens-103 &
az group delete -y --no-wait -g east-ga-athens-104 &
az group delete -y --no-wait -g east-ga-athens-105 &
az group delete -y --no-wait -g east-ga-atl-101 &
az group delete -y --no-wait -g east-ga-atl-102 &
az group delete -y --no-wait -g east-ga-atl-103 &
az group delete -y --no-wait -g east-ga-atl-104 &
az group delete -y --no-wait -g east-ga-atl-105 &
az group delete -y --no-wait -g east-ga-north-101 &
az group delete -y --no-wait -g east-ga-north-102 &
az group delete -y --no-wait -g east-ga-north-103 &
az group delete -y --no-wait -g east-ga-north-104 &
az group delete -y --no-wait -g east-ga-north-105 &
az group delete -y --no-wait -g east-ga-south-101 &
az group delete -y --no-wait -g east-ga-south-102 &
az group delete -y --no-wait -g east-ga-south-103 &
az group delete -y --no-wait -g east-ga-south-104 &
az group delete -y --no-wait -g east-ga-south-105 &
az group delete -y --no-wait -g east-nc-charlotte-101 &
az group delete -y --no-wait -g east-nc-charlotte-102 &
az group delete -y --no-wait -g east-nc-charlotte-103 &
az group delete -y --no-wait -g east-nc-charlotte-104 &
az group delete -y --no-wait -g east-nc-charlotte-105 &
az group delete -y --no-wait -g east-nc-durham-101 &
az group delete -y --no-wait -g east-nc-durham-102 &
az group delete -y --no-wait -g east-nc-durham-103 &
az group delete -y --no-wait -g east-nc-durham-104 &
az group delete -y --no-wait -g east-nc-durham-105 &
az group delete -y --no-wait -g east-nc-east-101 &
az group delete -y --no-wait -g east-nc-east-102 &
az group delete -y --no-wait -g east-nc-east-103 &
az group delete -y --no-wait -g east-nc-east-104 &
az group delete -y --no-wait -g east-nc-east-105 &
az group delete -y --no-wait -g east-nc-raleigh-101 &
az group delete -y --no-wait -g east-nc-raleigh-102 &
az group delete -y --no-wait -g east-nc-raleigh-103 &
az group delete -y --no-wait -g east-nc-raleigh-104 &
az group delete -y --no-wait -g east-nc-raleigh-105 &
az group delete -y --no-wait -g east-nc-west-101 &
az group delete -y --no-wait -g east-nc-west-102 &
az group delete -y --no-wait -g east-nc-west-103 &
az group delete -y --no-wait -g east-nc-west-104 &
az group delete -y --no-wait -g east-nc-west-105 &
az group delete -y --no-wait -g west-ca-la-101 &
az group delete -y --no-wait -g west-ca-la-102 &
az group delete -y --no-wait -g west-ca-la-103 &
az group delete -y --no-wait -g west-ca-la-104 &
az group delete -y --no-wait -g west-ca-la-105 &
az group delete -y --no-wait -g west-ca-north-101 &
az group delete -y --no-wait -g west-ca-north-102 &
az group delete -y --no-wait -g west-ca-north-103 &
az group delete -y --no-wait -g west-ca-north-104 &
az group delete -y --no-wait -g west-ca-north-105 &
az group delete -y --no-wait -g west-ca-sac-101 &
az group delete -y --no-wait -g west-ca-sac-102 &
az group delete -y --no-wait -g west-ca-sac-103 &
az group delete -y --no-wait -g west-ca-sac-104 &
az group delete -y --no-wait -g west-ca-sac-105 &
az group delete -y --no-wait -g west-ca-sand-101 &
az group delete -y --no-wait -g west-ca-sand-102 &
az group delete -y --no-wait -g west-ca-sand-103 &
az group delete -y --no-wait -g west-ca-sand-104 &
az group delete -y --no-wait -g west-ca-sand-105 &
az group delete -y --no-wait -g west-ca-sfo-101 &
az group delete -y --no-wait -g west-ca-sfo-102 &
az group delete -y --no-wait -g west-ca-sfo-103 &
az group delete -y --no-wait -g west-ca-sfo-104 &
az group delete -y --no-wait -g west-ca-sfo-105 &
az group delete -y --no-wait -g west-ca-south-101 &
az group delete -y --no-wait -g west-ca-south-102 &
az group delete -y --no-wait -g west-ca-south-103 &
az group delete -y --no-wait -g west-ca-south-104 &
az group delete -y --no-wait -g west-ca-south-105 &
az group delete -y --no-wait -g west-ca-west-101 &
az group delete -y --no-wait -g west-ca-west-102 &
az group delete -y --no-wait -g west-ca-west-103 &
az group delete -y --no-wait -g west-ca-west-104 &
az group delete -y --no-wait -g west-ca-west-105 &
az group delete -y --no-wait -g west-wa-central-101 &
az group delete -y --no-wait -g west-wa-central-102 &
az group delete -y --no-wait -g west-wa-central-103 &
az group delete -y --no-wait -g west-wa-central-104 &
az group delete -y --no-wait -g west-wa-central-105 &
az group delete -y --no-wait -g west-wa-east-101 &
az group delete -y --no-wait -g west-wa-east-102 &
az group delete -y --no-wait -g west-wa-east-103 &
az group delete -y --no-wait -g west-wa-east-104 &
az group delete -y --no-wait -g west-wa-east-105 &
az group delete -y --no-wait -g west-wa-olympia-101 &
az group delete -y --no-wait -g west-wa-olympia-102 &
az group delete -y --no-wait -g west-wa-olympia-103 &
az group delete -y --no-wait -g west-wa-olympia-104 &
az group delete -y --no-wait -g west-wa-olympia-105 &
az group delete -y --no-wait -g west-wa-sea-101 &
az group delete -y --no-wait -g west-wa-sea-102 &
az group delete -y --no-wait -g west-wa-sea-103 &
az group delete -y --no-wait -g west-wa-sea-104 &
az group delete -y --no-wait -g west-wa-sea-105 &
az group delete -y --no-wait -g west-wa-spokane-101 &
az group delete -y --no-wait -g west-wa-spokane-102 &
az group delete -y --no-wait -g west-wa-spokane-103 &
az group delete -y --no-wait -g west-wa-spokane-104 &
az group delete -y --no-wait -g west-wa-spokane-105 &
az group delete -y --no-wait -g west-wa-tacoma-101 &
az group delete -y --no-wait -g west-wa-tacoma-102 &
az group delete -y --no-wait -g west-wa-tacoma-103 &
az group delete -y --no-wait -g west-wa-tacoma-104 &
az group delete -y --no-wait -g west-wa-tacoma-105 &
az group delete -y --no-wait -g west-wa-west-101 &
az group delete -y --no-wait -g west-wa-west-102 &
az group delete -y --no-wait -g west-wa-west-103 &
az group delete -y --no-wait -g west-wa-west-104 &
az group delete -y --no-wait -g west-wa-west-105 &


# remove IPs
rm -f "$(dirname "${BASH_SOURCE[0]}")/ips"
rm ~/.ssh/known_hosts
