apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: vtlog
    istio-injection: enabled
  name: vtlog

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtlog
  namespace: vtlog
  labels:
    app.kubernetes.io/name: vtlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtlog
  template:
    metadata:
      labels:
        app: vtlog
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/vtlog:latest
          imagePullPolicy: Always
          args:
          - --region
          - wabrez
          - --zone
          - wabrez-wa-seattle
          - --district
          - wabrez-wa-seattle
          - --store
          - wabrez-wa-seattle-105
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /tlog/readyz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            httpGet:
              path: /tlog/healthz
              port: 8080
          resources:
            limits:
              cpu: 400m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: vtlog
  namespace: vtlog
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vtlog

---

apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: vtlog-gateway
  namespace: vtlog
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "wabrez-wa-seattle-105.cseretail.com"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "wabrez-wa-seattle-105.cseretail.com"
      tls:
        mode: SIMPLE
        credentialName: ssl-cert
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vtlog-vs
  namespace: vtlog
spec:
  hosts:
    - "wabrez-wa-seattle-105.cseretail.com"
  gateways:
    - vtlog-gateway
  http:
    - match:
        - uri:
            prefix: "/tlog"
      rewrite:
        uri: "/tlog"
      route:
        - destination:
            host: vtlog
            port:
              number: 8080
