apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: vtlog
    istio-injection: enabled
  name: vtlog

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtlog
  namespace: vtlog
  labels:
    app.kubernetes.io/name: vtlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtlog
  template:
    metadata:
      labels:
        app: vtlog
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/vtlog:beta
          imagePullPolicy: Always
          args:
          - --region
          - central
          - --zone
          - central-tx
          - --district
          - central-tx-bartr
          - --store
          - central-tx-bartr-101
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /readyz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            httpGet:
              path: /healthz
              port: 8080
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: vtlog
  namespace: vtlog
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vtlog
