#!/bin/bash

#name: deploy
#short: Deploy your app to the local cluster

# delete the existing apps
kubectl delete -f deploy/namespace.yaml

# deploy the app
kubectl apply -f deploy
kubectl apply -f deploy/app

# deploy bootstrap
kubectl apply -f deploy/bootstrap
kubectl apply -R -f deploy/bootstrap

# deploy WebV after the app starts
kubectl wait pod -l app=testapp -n testapp --for condition=ready --timeout=60s
kubectl apply -f deploy/webv
